---
title: "Covid Project"
output:   
  github_document:
    toc: true
---

```{r setup}
library(tidyverse)
```
Download Population data
```{r}
df_pop_no_fips <- read_csv("data/ACSDT5Y2018.B01003_data_with_overlays_2020-10-06T142714.csv", skip = 1)
df_pop_no_fips %>% glimpse

df_population <- 
  df_pop_no_fips %>% 
  separate(col = id, into = c("id_head", "fips"), sep = "US") %>% 
  subset(select = -c(id_head))
```
```{r}
df_covid <- read_csv(filename_nyt) 
df_covid %>%
  select(date) %>%
  unique() %>%
  arrange(desc(date)) %>%
  head(20)
```
Download COVID data
```{r}
url_counties_covid <- "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"
filename_nyt <- "./data/nyt_counties.csv"

## Download the data locally
curl::curl_download(
        url_counties_covid,
        destfile = filename_nyt
      )


most_recent_date <- df_normalized %>%
  select(date) %>%
  arrange(desc(date)) %>%
  head(1)
## Loads the downloaded csv
df_covid <- read_csv(filename_nyt) 

most_recent_date <- df_covid %>%
  select(date) %>%
  arrange(desc(date)) %>%
  head(1)

df_covid <- df_covid %>%
  filter(date==most_recent_date)
  
df_covid %>% glimpse

```
Download Political data 
```{r}
url_counties_political <- "https://raw.githubusercontent.com/tonmcg/US_County_Level_Election_Results_08-16/master/2016_US_County_Level_Presidential_Results.csv"
filename_political <- "./data/political_counties.csv"

## Download the data locally
curl::curl_download(
        url_counties_political,
        destfile = filename_political
      )

## Loads the downloaded csv
df_political <- read_csv(filename_political)
df_political <- df_political %>%
  rename(
    fips = combined_fips,
    ) %>%
  subset(select = -c(X1))
df_political %>% glimpse

```
Combine data
```{r}
df_population_covid <- merge(df_population, df_covid,  by=c("fips")) %>%   
  select(
    date,
    county,
    state,
    fips,
    cases,
    deaths,
    population = `Estimate!!Total`
  ) %>%
  mutate(
    cases_per100k = (100000 / population) * cases,
    deaths_per100k = (100000 / population) * deaths
  ) 
df_population_covid_political <- merge(df_political, df_population_covid, by=c("fips")) %>%
  rename(
    county_fips = fips
  )
df_population_covid_political %>% glimpse
```
Add Map Data
```{r}
devtools::install_github('UrbanInstitute/urbnmapr')
library(urbnmapr)
df_population_covid_political$county_fips = as.character(df_population_covid_political$county_fips)
df_population_covid_political_with_map <- left_join(df_population_covid_political, counties, by = "county_fips")

df_population_covid_political_with_map %>% glimpse
```
```{r}
df_population_covid_political_with_map %>%
  ggplot(aes(long, lat, group = group, fill = deaths_per100k)) +
  geom_polygon(color = NA) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  labs(fill = "Cases")
```
```{r}
df_population_covid_political_with_map %>%
  filter(state_abbv == 'MA') %>% 
  ggplot(aes(long, lat, group = group, fill = cases_per100k)) +
  geom_polygon(color = NA) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  labs(fill = "Cases Per 100k")

df_population_covid_political_with_map %>%
  filter(state_abbv == 'MA') %>% 
  ggplot(aes(long, lat, group = group, fill = per_gop)) +
  geom_polygon(color = NA) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  scale_fill_gradientn(colours = c("blue", "red"),
                       labels = scales::percent,
                       guide = guide_colorbar(title.position = "top"),
                       colors = ) +
  labs(fill = "Voted Trump")
```
```{r}
df_population_covid_political_with_map %>%
  ggplot(aes(long, lat, group = group, fill = per_gop)) +
  geom_polygon(color = "#ffffff", size = .25) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  scale_fill_gradientn(colours = c("blue", "red"),
                       labels = scales::percent,
                       guide = guide_colorbar(title.position = "top"),
                       colors = ) +
  labs(fill = "Voted For Trump")
```

```{r}
counties %>% glimpse
```

